
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'About': typeof import("../components/About.vue")['default']
    'Button3D': typeof import("../components/Button3D.vue")['default']
    'CardProject': typeof import("../components/CardProject.vue")['default']
    'CardSkill': typeof import("../components/CardSkill.vue")['default']
    'ContactForm': typeof import("../components/ContactForm.vue")['default']
    'DivisionBottom': typeof import("../components/DivisionBottom.vue")['default']
    'DivisionTop': typeof import("../components/DivisionTop.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'MenuAside': typeof import("../components/MenuAside.vue")['default']
    'SlidesCertificates': typeof import("../components/SlidesCertificates.vue")['default']
    'IconsArroba': typeof import("../components/icons/Arroba.vue")['default']
    'IconsArrowLeft': typeof import("../components/icons/ArrowLeft.vue")['default']
    'IconsArrowRight': typeof import("../components/icons/ArrowRight.vue")['default']
    'IconsArrowTop': typeof import("../components/icons/ArrowTop.vue")['default']
    'IconsDownload': typeof import("../components/icons/Download.vue")['default']
    'IconsEmail': typeof import("../components/icons/Email.vue")['default']
    'IconsGitHub': typeof import("../components/icons/GitHub.vue")['default']
    'IconsInstagram': typeof import("../components/icons/Instagram.vue")['default']
    'IconsLink': typeof import("../components/icons/Link.vue")['default']
    'IconsLinkedin': typeof import("../components/icons/Linkedin.vue")['default']
    'IconsUser': typeof import("../components/icons/User.vue")['default']
    'IconsVolume': typeof import("../components/icons/Volume.vue")['default']
    'IconsLangCSS': typeof import("../components/icons/lang/CSS.vue")['default']
    'IconsLangDocker': typeof import("../components/icons/lang/Docker.vue")['default']
    'IconsLangGit': typeof import("../components/icons/lang/Git.vue")['default']
    'IconsLangHTML': typeof import("../components/icons/lang/HTML.vue")['default']
    'IconsLangJs': typeof import("../components/icons/lang/Js.vue")['default']
    'IconsLangLinux': typeof import("../components/icons/lang/Linux.vue")['default']
    'IconsLangMongoDB': typeof import("../components/icons/lang/MongoDB.vue")['default']
    'IconsLangNodeJs': typeof import("../components/icons/lang/NodeJs.vue")['default']
    'IconsLangVueJs': typeof import("../components/icons/lang/VueJs.vue")['default']
    'IconsLangWordPress': typeof import("../components/icons/lang/WordPress.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAbout': typeof import("../components/About.vue")['default']
    'LazyButton3D': typeof import("../components/Button3D.vue")['default']
    'LazyCardProject': typeof import("../components/CardProject.vue")['default']
    'LazyCardSkill': typeof import("../components/CardSkill.vue")['default']
    'LazyContactForm': typeof import("../components/ContactForm.vue")['default']
    'LazyDivisionBottom': typeof import("../components/DivisionBottom.vue")['default']
    'LazyDivisionTop': typeof import("../components/DivisionTop.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyMenuAside': typeof import("../components/MenuAside.vue")['default']
    'LazySlidesCertificates': typeof import("../components/SlidesCertificates.vue")['default']
    'LazyIconsArroba': typeof import("../components/icons/Arroba.vue")['default']
    'LazyIconsArrowLeft': typeof import("../components/icons/ArrowLeft.vue")['default']
    'LazyIconsArrowRight': typeof import("../components/icons/ArrowRight.vue")['default']
    'LazyIconsArrowTop': typeof import("../components/icons/ArrowTop.vue")['default']
    'LazyIconsDownload': typeof import("../components/icons/Download.vue")['default']
    'LazyIconsEmail': typeof import("../components/icons/Email.vue")['default']
    'LazyIconsGitHub': typeof import("../components/icons/GitHub.vue")['default']
    'LazyIconsInstagram': typeof import("../components/icons/Instagram.vue")['default']
    'LazyIconsLink': typeof import("../components/icons/Link.vue")['default']
    'LazyIconsLinkedin': typeof import("../components/icons/Linkedin.vue")['default']
    'LazyIconsUser': typeof import("../components/icons/User.vue")['default']
    'LazyIconsVolume': typeof import("../components/icons/Volume.vue")['default']
    'LazyIconsLangCSS': typeof import("../components/icons/lang/CSS.vue")['default']
    'LazyIconsLangDocker': typeof import("../components/icons/lang/Docker.vue")['default']
    'LazyIconsLangGit': typeof import("../components/icons/lang/Git.vue")['default']
    'LazyIconsLangHTML': typeof import("../components/icons/lang/HTML.vue")['default']
    'LazyIconsLangJs': typeof import("../components/icons/lang/Js.vue")['default']
    'LazyIconsLangLinux': typeof import("../components/icons/lang/Linux.vue")['default']
    'LazyIconsLangMongoDB': typeof import("../components/icons/lang/MongoDB.vue")['default']
    'LazyIconsLangNodeJs': typeof import("../components/icons/lang/NodeJs.vue")['default']
    'LazyIconsLangVueJs': typeof import("../components/icons/lang/VueJs.vue")['default']
    'LazyIconsLangWordPress': typeof import("../components/icons/lang/WordPress.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const About: typeof import("../components/About.vue")['default']
export const Button3D: typeof import("../components/Button3D.vue")['default']
export const CardProject: typeof import("../components/CardProject.vue")['default']
export const CardSkill: typeof import("../components/CardSkill.vue")['default']
export const ContactForm: typeof import("../components/ContactForm.vue")['default']
export const DivisionBottom: typeof import("../components/DivisionBottom.vue")['default']
export const DivisionTop: typeof import("../components/DivisionTop.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const MenuAside: typeof import("../components/MenuAside.vue")['default']
export const SlidesCertificates: typeof import("../components/SlidesCertificates.vue")['default']
export const IconsArroba: typeof import("../components/icons/Arroba.vue")['default']
export const IconsArrowLeft: typeof import("../components/icons/ArrowLeft.vue")['default']
export const IconsArrowRight: typeof import("../components/icons/ArrowRight.vue")['default']
export const IconsArrowTop: typeof import("../components/icons/ArrowTop.vue")['default']
export const IconsDownload: typeof import("../components/icons/Download.vue")['default']
export const IconsEmail: typeof import("../components/icons/Email.vue")['default']
export const IconsGitHub: typeof import("../components/icons/GitHub.vue")['default']
export const IconsInstagram: typeof import("../components/icons/Instagram.vue")['default']
export const IconsLink: typeof import("../components/icons/Link.vue")['default']
export const IconsLinkedin: typeof import("../components/icons/Linkedin.vue")['default']
export const IconsUser: typeof import("../components/icons/User.vue")['default']
export const IconsVolume: typeof import("../components/icons/Volume.vue")['default']
export const IconsLangCSS: typeof import("../components/icons/lang/CSS.vue")['default']
export const IconsLangDocker: typeof import("../components/icons/lang/Docker.vue")['default']
export const IconsLangGit: typeof import("../components/icons/lang/Git.vue")['default']
export const IconsLangHTML: typeof import("../components/icons/lang/HTML.vue")['default']
export const IconsLangJs: typeof import("../components/icons/lang/Js.vue")['default']
export const IconsLangLinux: typeof import("../components/icons/lang/Linux.vue")['default']
export const IconsLangMongoDB: typeof import("../components/icons/lang/MongoDB.vue")['default']
export const IconsLangNodeJs: typeof import("../components/icons/lang/NodeJs.vue")['default']
export const IconsLangVueJs: typeof import("../components/icons/lang/VueJs.vue")['default']
export const IconsLangWordPress: typeof import("../components/icons/lang/WordPress.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAbout: typeof import("../components/About.vue")['default']
export const LazyButton3D: typeof import("../components/Button3D.vue")['default']
export const LazyCardProject: typeof import("../components/CardProject.vue")['default']
export const LazyCardSkill: typeof import("../components/CardSkill.vue")['default']
export const LazyContactForm: typeof import("../components/ContactForm.vue")['default']
export const LazyDivisionBottom: typeof import("../components/DivisionBottom.vue")['default']
export const LazyDivisionTop: typeof import("../components/DivisionTop.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyMenuAside: typeof import("../components/MenuAside.vue")['default']
export const LazySlidesCertificates: typeof import("../components/SlidesCertificates.vue")['default']
export const LazyIconsArroba: typeof import("../components/icons/Arroba.vue")['default']
export const LazyIconsArrowLeft: typeof import("../components/icons/ArrowLeft.vue")['default']
export const LazyIconsArrowRight: typeof import("../components/icons/ArrowRight.vue")['default']
export const LazyIconsArrowTop: typeof import("../components/icons/ArrowTop.vue")['default']
export const LazyIconsDownload: typeof import("../components/icons/Download.vue")['default']
export const LazyIconsEmail: typeof import("../components/icons/Email.vue")['default']
export const LazyIconsGitHub: typeof import("../components/icons/GitHub.vue")['default']
export const LazyIconsInstagram: typeof import("../components/icons/Instagram.vue")['default']
export const LazyIconsLink: typeof import("../components/icons/Link.vue")['default']
export const LazyIconsLinkedin: typeof import("../components/icons/Linkedin.vue")['default']
export const LazyIconsUser: typeof import("../components/icons/User.vue")['default']
export const LazyIconsVolume: typeof import("../components/icons/Volume.vue")['default']
export const LazyIconsLangCSS: typeof import("../components/icons/lang/CSS.vue")['default']
export const LazyIconsLangDocker: typeof import("../components/icons/lang/Docker.vue")['default']
export const LazyIconsLangGit: typeof import("../components/icons/lang/Git.vue")['default']
export const LazyIconsLangHTML: typeof import("../components/icons/lang/HTML.vue")['default']
export const LazyIconsLangJs: typeof import("../components/icons/lang/Js.vue")['default']
export const LazyIconsLangLinux: typeof import("../components/icons/lang/Linux.vue")['default']
export const LazyIconsLangMongoDB: typeof import("../components/icons/lang/MongoDB.vue")['default']
export const LazyIconsLangNodeJs: typeof import("../components/icons/lang/NodeJs.vue")['default']
export const LazyIconsLangVueJs: typeof import("../components/icons/lang/VueJs.vue")['default']
export const LazyIconsLangWordPress: typeof import("../components/icons/lang/WordPress.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
